### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [EliCDavis/mesh#2]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by EliCDavis** [comment]
MIT. I'll add a license right now.

I'm starting to build a more refined version [here](https://github.com/EliCDavis/mango) that will follow along with a [youtube series](https://youtu.be/uM5EykxswWs).

Let me know if you have any specific questions / Topics you want to learn.

**Comment by EliCDavis** [comment]
License added. Please open up a new issue if you need anything else.
